### ISSUE TITLE
(void-function incf) problem

### ISSUE THREAD

**Issue by ardumont** [rejeep/el-mock.el#18]
Hello, 

@rejeep First thanks for all your tools/libraries (evm, cask, f, ...), it helps quite a lot.

I have the same issue across multiple repositories of mine about the `incf` function being void.
Here is an excerpt:
```
F.Test test-org2jekyll-read-metadata-and-execute backtrace:

  (let ((filename-non-dir (file-name-nondirectory org-file))) (if (org
  org2jekyll-read-metadata-and-execute((lambda (org-metadata org-file)
  (lambda nil (org2jekyll-read-metadata-and-execute (function (lambda
  #[nil "\302\30!!\210   \207" [spec body-func eval mock-parse-spec]
  mock-protect(#[nil "\302\30!!\210      \207" [spec body-func eval mock
  mocklet-function((((org2jekyll-article-p "org-file") => t) ((file-na
  (list "Post 'some-org-file' published!" (mocklet-function (quote (((
  (let ((fn-244 (function equal)) (args-245 (list "Post 'some-org-file
  (lambda nil (let ((fn-244 (function equal)) (args-245 (list "Post 's
  ert--run-test-internal([cl-struct-ert--test-execution-info [cl-struc
  ert-run-test([cl-struct-ert-test test-org2jekyll-read-metadata-and-e
  ert-run-or-rerun-test([cl-struct-ert--stats (and t) [[cl-struct-ert-
  ert-run-tests((and t) (lambda (event-type &rest event-args) (cond ((
  ert-runner/run-tests-batch((and t))
  (let ((stats (ert-runner/run-tests-batch selector))) (kill-emacs (if
  ert-runner/run-tests-batch-and-exit((and t))
  (if ert-runner-verbose (ert-runner/run-tests-batch-and-exit ert-runn
  (let ((test-files (ert-runner--test-files tests)) (test-helper (f-ex
  ert-runner/run()
  apply(ert-runner/run nil)
  commander--handle-command(nil)
  commander-parse(nil)
  (if commander-parsing-done nil (commander-parse (or commander-args (
  eval-buffer(#<buffer  *load*> nil "/home/tony/repo/public/org2jekyll
  load-with-code-conversion("/home/tony/repo/public/org2jekyll/.cask/2
  load("/home/tony/repo/public/org2jekyll/.cask/25.1/elpa/ert-runner-2
  command-line-1(("-scriptload" "/home/tony/repo/public/org2jekyll/.ca
  command-line()
  normal-top-level()

Test test-org2jekyll-read-metadata-and-execute condition:

    (void-function incf)
```
[You can see a full build example with 4 emacs version with similar error](https://travis-ci.org/ardumont/org2jekyll/builds/205228528)

They have all in common that i use the same toolset (travis, evm, cask, ert-runner) including el-mock.
And it seems to be the source of the problem.

At first, in the test context, I added this snippet which solved the problem on a per repository basis:
```
(require 'cl-lib)
(defalias 'incf 'cl-incf)
```
But it's inconvenient because it duplicates a fix. And that fix is not that repository's concern anyway.

So thinking of another solution and i thought of patching the cask installed el-mock version to check my assertion is correct.
Implementation wise, i just replaced the only instance of `incf` by `cl-incf` since cl-lib is already required.
And it fixed it as well.

I prefer this solution as this seems more like the fix's perimeter.

Do you agree with my reasoning?
If so, would you accept a PR about it?

Cheers,

**Comment by ardumont** [comment]
> If so, would you accept a PR about it?

#19 is the PR that fix the issue (implementing solution 2).

**Comment by rejeep** [comment]
Closing this in favour of #19
