### ISSUE TITLE
Missing arguments in mock calls are ignored

### ISSUE THREAD

**Issue by phst** [rejeep/el-mock.el#5]
Example:

```lisp
(with-mock
  (mock (f 1 2))
  (f))
```

I'd expect this to raise an error, but it doesn't.

**Comment by rejeep** [comment]
That's probably a bug, yes. I noticed that if you call `f` with any argument, it fails. I you want to write a fix for it that would be great.

**Comment by phst** [comment]
Sent a pull request.
